# Configuration File for the heron specific modelling endpoints

# Paths to Python classes should be absolute to avoid import errors

# Heron tracker service base URL
heron.tracker.url: 'http://heron-tracker-new.prod.heron.service.{zone}.twitter.com/'

# The metrics client to use for Heron topologies
heron.metrics.client: 'caladrius.metrics.heron.cuckoo.heron_cuckoo_client.HeronTwitterCuckooClient'

# Config arguments for the heron metrics client
heron.metrics.client.config: 
    database.url: 'https://cuckoo-prod-{zone}.twitter.biz/'
    default.zone: 'smf1'
    
# List of Heron traffic models
model.traffic.heron:
    - 'caladrius.model.traffic.heron.dummy_traffic.DummyTrafficModel'

# List of Heron topology performance models for currently deployed topologies
# with different arrival rates
model.topology.heron.current:
    - 'caladrius.model.topology.heron.CurrentTopologyModel'

# List of Heron topology performance models for modelling the performance of
# proposed packing plans
model.topology.heron.proposed:
    - 'caladrius.model.topology.heron.QueuingTheoryModel'
