## CALADRIUS CONFIG ##

log.file.dir: "/tmp/caladrius/logs"

## GRAPH CONFIG ##

graph.client: 'caladrius.graph.gremlin.client.GremlinClient'

graph.client.config:
    gremlin.server.url : "localhost:8182"

## HERON CONFIG ##

# The metrics client to use for Heron topologies
heron.metrics.client: 'caladrius.metrics.heron.myclient.client.MyMetricsClient'

heron.metrics.client.config:
    myclient.database.url: "https://my-metrics-database.com"
    myclient.client.name: "MyClient-Name"

heron.tracker.url: "http://heron-tracker.com"

heron.traffic.models:
    - "caladrius.model.traffic.heron.basic_stats.BasicStatsTrafficModel"

heron.traffic.models.config:
    basicstats.model.default.hours: 24


