# Main Caladrius configuration file

# Paths to Python classes should be absolute to avoid import errors

# Base address for the API data store server
caladrius.api.datastore.address: 'localhost:8080'

# Graph Database connection url
caladrius.graph.db.url: 'localhost:8182'


###### HERON #######

# Heron tracker service base URL
heron.tracker.url: 'http://heron-tracker-example.com/'

# The metrics client to use for Heron topologies
heron.metrics.client: 'caladrius.metrics.heron.metrics_database.client.MyMetricsClient'

# Config arguments for the heron metrics client
heron.metrics.client.config: 
    database.url: 'https://metrics-db.com/'
    client.name: 'My-Metrics-client'
    
# List of Heron traffic models
model.traffic.heron:
    - 'caladrius.model.traffic.heron.dummy_traffic.DummyTrafficModel'

# List of Heron topology performance models for currently deployed topologies
# with different arrival rates
model.topology.heron.current:
    - 'caladrius.model.topology.heron.CurrentTopologyModel'

# List of Heron topology performance models for modelling the performance of
# proposed packing plans
model.topology.heron.proposed:
    - 'caladrius.model.topology.heron.QueuingTheoryModel'




