# Main Caladrius configuration file

# Base address for the API data store server
caladrius.api.datastore.address: 'localhost:8080'

# Graph Database connection url
caladrius.graph.db.url: 'localhost:8182'





