## CALADRIUS CONFIG ##

log.file.dir: "/tmp/caladrius/logs"

## GRAPH CONFIG ##

graph.client: 'caladrius.graph.gremlin.client.GremlinClient'

graph.client.config:
    gremlin.server.url : "localhost:8182"

## HERON CONFIG ##

# The metrics client to use for Heron topologies
# To use the Caladrius Cuckoo client:
# $ git clone https://git.twitter.biz/caladrius_cuckoo/
# Add the folder above the repo to you python path:
# $ export PYTHONPATH=$PYTHONPATH:folder/above/caladrius_cuckoo/repo
heron.metrics.client: 'caladrius_cuckoo.client.HeronCuckooClient'

heron.metrics.client.config:
    cuckoo.database.url: "https://cuckoo-prod-smf1.twitter.biz"
    cuckoo.client.name: "Infra-Caladrius"
    cuckoo.client.max.batch.length: 6.0
    cuckoo.client.max.retry: 10

heron.tracker.url: "http://heron-tracker-new.prod.heron.service.smf1.twitter.com"

heron.traffic.models:
    - "caladrius.model.traffic.heron.stats_summary.StatsSummaryTrafficModel"
    - "caladrius.model.traffic.heron.prophet.ProphetTrafficModel"

# This map is passed to all Traffic models at start up
heron.traffic.models.config:
    heron.tracker.url: "http://heron-tracker-new.prod.heron.service.smf1.twitter.com"
    stats.summary.model.default.source.hours: 24
    stats.summary.model.quantiles:
        - 10
        - 90
        - 95
        - 99
    heron.statemgr.connection.string: 'szookeeper.smf1.twitter.com'
    heron.statemgr.root.path: 'tree/storm/heron/states'
    zk.time.offset: -5
    prophet.model.default.future.mins: 30
    # 60 has units seconds
    prophet.model.default.metrics_sample_period: 60
    prophet.model.default.source.hours: 24
    prophet.model.quantiles:
        - 10
        - 90
        - 95
        - 99

heron.topology.models:
    - "caladrius.model.topology.heron.queueing_theory.QTTopologyModel"

# This map is passed to all Topology models at start up
heron.topology.models.config:
    heron.statemgr.connection.string: 'szookeeper.smf1.twitter.com'
    heron.statemgr.root.path: 'tree/storm/heron/states'
    zk.time.offset: -5
    metric.bucket.length: 120
    heron.tracker.url: "http://heron-tracker-new.prod.heron.service.smf1.twitter.com"


# This map is for configuring models for proposed packing plans.
heron.packingpplans.models.config:
    heron.statemgr.connection.string: 'szookeeper.smf1.twitter.com'
    heron.statemgr.root.path: 'tree/storm/heron/states'
    zk.time.offset: -5
    metric.bucket.length: 120
    heron.tracker.url: "http://heron-tracker-new.prod.heron.service.smf1.twitter.com"
